//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace deo_report_test
{
    using System;
    using System.Collections.Generic;
    
    public partial class dep_excel
    {
        public int id { get; set; }
        public string dasaxeleba { get; set; }
        public string qalaqi { get; set; }
        public string raioni { get; set; }
        public string municipaliteti { get; set; }
        public string daba { get; set; }
        public string sofeli { get; set; }
    }
}
